from common import *

page_setup()

show_header('Reports with Export')
report = st.selectbox('Select Report', ['Pallet Wise Balance Quantity', 'Original Invoice Wise Balance Quantity', 'Payment Due Summary Invoice Wise', 'Delivery Invoice Wise Summary Report', 'Monthly Sales Report - Product and Customer', 'Monthly Payment Receipt Report'])
if report == 'Pallet Wise Balance Quantity':
    rows = fetch_all('\n                SELECT s.shipment_no, s.invoice_no, b.pallet_no, b.box_no, p.product_code, p.product_name,\n                       b.original_qty, b.unit_price, b.currency, b.amount,\n                       IFNULL(SUM(d.delivered_qty),0) delivered_qty,\n                       b.original_qty - IFNULL(SUM(d.delivered_qty),0) balance_qty\n                FROM shipment_boxes b\n                JOIN shipments s ON b.shipment_id = s.id\n                JOIN products p ON b.product_id = p.id\n                LEFT JOIN customer_deliveries d ON b.id = d.box_id\n               GROUP BY\n    b.id,\n    s.shipment_no,\n    s.invoice_no,\n    b.pallet_no,\n    b.box_no,\n    p.product_code,\n    p.product_name,\n    b.original_qty,\n    b.unit_price,\n    b.currency,\n    b.amount\n                ORDER BY s.shipment_no, b.pallet_no, b.box_no\n            ')
elif report == 'Original Invoice Wise Balance Quantity':
    rows = fetch_all('\n                SELECT s.invoice_no, s.shipment_no, p.product_code, p.product_name,\n                       SUM(b.original_qty) original_qty, SUM(b.amount) amount,\n                       IFNULL(SUM(d.delivered_qty),0) delivered_qty,\n                       SUM(b.original_qty) - IFNULL(SUM(d.delivered_qty),0) balance_qty\n                FROM shipment_boxes b\n                JOIN shipments s ON b.shipment_id = s.id\n                JOIN products p ON b.product_id = p.id\n                LEFT JOIN customer_deliveries d ON b.id = d.box_id\n                GROUP BY s.invoice_no, s.shipment_no, p.product_code, p.product_name\n                ORDER BY s.invoice_no\n            ')
elif report == 'Payment Due Summary Invoice Wise':
    rows = fetch_all("\n                SELECT d.delivery_invoice_no, c.customer_name, d.delivery_date, d.payment_due_date,\n                       pt.term_name, SUM(d.delivered_qty) delivered_qty, d.currency, SUM(d.sale_amount) sale_amount,\n                       IFNULL(SUM(p.payment_amount),0) paid_amount,\n                       SUM(d.sale_amount) - IFNULL(SUM(p.payment_amount),0) pending_amount,\n                       CASE WHEN SUM(d.sale_amount) - IFNULL(SUM(p.payment_amount),0) <= 0 THEN 'Paid'\n                            WHEN date(MAX(d.payment_due_date)) < date('now') THEN 'Overdue'\n                            ELSE 'Pending' END payment_status\n                FROM customer_deliveries d\n                JOIN customers c ON d.customer_id = c.id\n                LEFT JOIN payment_terms pt ON d.payment_term_id = pt.id\n                LEFT JOIN payments p ON d.id = p.delivery_id\n                GROUP BY d.delivery_invoice_no, c.customer_name, d.currency\n                ORDER BY d.payment_due_date\n            ")
elif report == 'Delivery Invoice Wise Summary Report':
    rows = fetch_all('\n                SELECT d.delivery_invoice_no, c.customer_name, s.invoice_no AS original_invoice_no,\n                       s.shipment_no, MIN(d.delivery_date) delivery_date, MAX(d.payment_due_date) payment_due_date,\n                       d.currency, SUM(d.delivered_qty) total_qty, SUM(d.sale_amount) total_amount,\n                       COUNT(d.id) product_rows\n                FROM customer_deliveries d\n                JOIN customers c ON d.customer_id = c.id\n                JOIN shipments s ON d.shipment_id = s.id\n                GROUP BY d.delivery_invoice_no, c.customer_name, s.invoice_no, s.shipment_no, d.currency\n                ORDER BY MIN(d.id) DESC\n            ')
elif report == 'Monthly Sales Report - Product and Customer':
    rows = fetch_all("\n                SELECT strftime('%Y-%m', d.delivery_date) sales_month,\n                       c.customer_name, p.product_code, p.product_name, d.currency,\n                       SUM(d.delivered_qty) total_qty,\n                       SUM(d.sale_amount) total_sales\n                FROM customer_deliveries d\n                JOIN customers c ON d.customer_id = c.id\n                JOIN shipment_boxes b ON d.box_id = b.id\n                JOIN products p ON b.product_id = p.id\n                GROUP BY sales_month, c.customer_name, p.product_code, p.product_name, d.currency\n                ORDER BY sales_month DESC, c.customer_name, p.product_code\n            ")
else:
    rows = fetch_all("\n                SELECT strftime('%Y-%m', p.payment_received_date) receipt_month,\n                       c.customer_name, d.delivery_invoice_no, s.invoice_no AS original_invoice_no,\n                       p.payment_reference, p.payment_received_date, p.payment_amount, p.remarks\n                FROM payments p\n                JOIN customer_deliveries d ON p.delivery_id = d.id\n                JOIN shipments s ON d.shipment_id = s.id\n                JOIN customers c ON d.customer_id = c.id\n                ORDER BY p.payment_received_date DESC, p.id DESC\n            ")
df = show_filtered_df(rows, f'reports_filter_{report}', total=True)
export_buttons(df, report.replace(' ', '_').replace('-', '').lower())

st.markdown('<div class="footer">COPYRIGHT BY FOUR STAR INDUSTRIES PVT. LTD.</div>', unsafe_allow_html=True)
